### ISSUE TITLE
Output to ELK

### ISSUE THREAD

**Issue by richard-hulm** [TykTechnologies/tyk-pump#1]
A brilliant feature would be creating an output to Elasticsearch, as that's a powerful tool for analytics such as this

Could use something like this https://github.com/olivere/elastic

We (Crunch) may look at doing a pull request if we create this functionality at some point, but thought I'd make an Issue here so it could be tracked

Cheers,

**Comment by lonelycode** [comment]
Very good idea, will put it on the list :-)

**Comment by richard-hulm** [comment]
Added basic import into ES functionality in https://github.com/TykTechnologies/tyk-pump/pull/3

**Comment by lonelycode** [comment]
:heart:
