### ISSUE TITLE
Allow Pumps to Identify Keys

### ISSUE THREAD

**Issue by JosephEarl** [TykTechnologies/tyk-pump#10]
Currently Pumps can track AnalyticsRecord anonymously e.g. based on API Key. When a key is created more information is available that can be used associate this API key with more permanent user information such as email address/username, Tyk developer ID and meta fields.

With this information it would be possible to track developers across key changes.

Specifically in the case of the Segment pump this information can be used with the Identify operation https://segment.com/docs/libraries/go/#identify.

**Comment by lonelycode** [comment]
Not sure about that - it kind of exposes a lot of secure data. I'd suggest looking at centralised JWT access, as this enables diferent keys to reference a single underlying identity across tokens

**Comment by JosephEarl** [comment]
Even if the user only has a single key this is still useful to be able to identify the user in the third party analytics or CSV. 

Currently to identify keys we have to:

1. Get a list of unique keys
2. Look them up using the Tyk API
3. Get the tyk_developer_id from the meta data if it has one
4. Look up the developer information using the Tyk API

This could also be useful for e.g. the CSV pump to identify keys created by developers.

**Comment by lonelycode** [comment]
How are you creating your keys? If you create the key with meta data, and then use the header injector to inject that metadata into your inbound requests, then it will also be recorded in your analytics.

**Comment by JosephEarl** [comment]
Keys are created through the portal (by developers requesting them) and approved in the dashboard - authentication mode is Auth token.

**Comment by JosephEarl** [comment]
Thanks, I'll look at injecting those fields into the request headers.

**Comment by lonelycode** [comment]
I'm not sure if the dev portal adds those fields - it will add their signup metadata definitely though. It's an interesting problem, so I think deserves a solution, but might need to be more selective (as in, you get to select what meta-data keys to store.

Will eave open - but this should really by in the Tyk repo as that's doing the analytics recording.

**Comment by JosephEarl** [comment]
It includes the signup fields, but not the email or signup date/time:

```
{
    "api_model": {},
    "key_id": "57060cc804ffc100090000014007fd88509147e3666c47227b32d22f",
    "data": {
        "last_check": 0,
        "allowance": 0,
        "rate": 0,
        "per": 0,
        "expires": 0,
        "quota_max": 0,
        "quota_renews": 1461088102,
        "quota_remaining": 0,
        "quota_renewal_rate": 0,
        "access_rights": {
            "2393c02e9c2d4f467e9d8735cd3eb132": {
                "api_name": "An API",
                "api_id": "2393c02e9c2d4f467e9d8735cd3eb132",
                "versions": ["Default"],
                "allowed_urls": []
            }
        },
        "org_id": "57060cc804ffc10009000001",
        "oauth_client_id": "",
        "basic_auth_data": {
            "password": "",
            "hash_type": ""
        },
        "jwt_data": {
            "secret": ""
        },
        "hmac_enabled": false,
        "hmac_string": "",
        "is_inactive": false,
        "apply_policy_id": "57060ce104ffc10009000021",
        "data_expires": 0,
        "monitor": {
            "trigger_limits": null
        },
        "meta_data": {
            "tyk_developer_id": "57166f4b2f6d9b0009000006",
            "tyk_key_request_fields": {},
            "tyk_user_fields": {
                "Company": "Acme Corp",
                "First Name": "A",
                "Last Name": "User",
                "Role": "Abc"
            }
        },
        "tags": null
    }
}
```

**Comment by lonelycode** [comment]
Ah, great - well that's a start without having to inject new analytics fields (not that it's hard)

Date/time is a good idea.

**Comment by JosephEarl** [comment]
Having the `tyk_developer_id` should be enough. In that case I don't think there is anything to be done on the pumps, so will close this.

What would be good in combination with injecting the `tyk_developer_id` is way to export Developers from Tyk (CSV/custom integration). This would be useful for looking at things like signup rate. I'll raise an issue for that in the Tyk repo.
