### ISSUE TITLE
logrus.Fields

### ISSUE THREAD

**Issue by idohalevi** [TykTechnologies/tyk-pump#100]
I keep getting the following error (using Goland) even after installing all the imports when the code uses `log.WithFields(logrus.Fields{})`

The error is:
![image](https://user-images.githubusercontent.com/32218210/54355592-24398700-4662-11e9-9e86-fe9a67514fb9.png)

Am I missing something?
Thanks

**Comment by buger** [comment]
What is the Go version you have?

**Comment by idohalevi** [comment]
@buger 
go1.9.2

**Comment by idohalevi** [comment]
@buger 
In addition, when I try to install all the dep using `go get -t -d -v ./...` I get an error. It seems like `github.com/influxdata/influxdb/client/v2` moved to `https://github.com/influxdata/influxdb1-client`

**Comment by buger** [comment]
In general, this code should be vendored to fixed version https://github.com/TykTechnologies/tyk-pump/tree/master/vendor/github.com/influxdata/influxdb/client/v2

**Comment by idohalevi** [comment]
@buger 
So what do you suggest to do? About both issues...
