### ISSUE TITLE
Create a new release with Prometheus metrics

### ISSUE THREAD

**Issue by carlosjgp** [TykTechnologies/tyk-pump#112]
Master branch already has the Prometheus pump it will be really useful to use the mainstream versions instead of compiling and creating our own Docker image to have access to this feature

Promethus metrics PR merged in February'19
https://github.com/TykTechnologies/tyk-pump/pull/91

Tyk pump: `v0.5.4` (October'18)
Docker image: `v0.5.4`
https://hub.docker.com/r/tykio/tyk-pump-docker-pub/tags

**Comment by asoorm** [comment]
Closing as released in https://github.com/TykTechnologies/tyk-pump/releases/tag/0.6.0
