### ISSUE TITLE
If endpoint path contains dot, then mongodb data gets corrupted

### ISSUE THREAD

**Issue by komalsukhani** [TykTechnologies/tyk-pump#113]
Analytics data for an endpoint is recorded in a field with name same as that of the path.
MongoDB doesn't support dot in the field name. If the path contains a dot, mongodb collection gets corrupted.

**Example**

If analytics is enabled for endpoint `/get/(.*)`, instead of creating field `/get/(.*)`, `/get/( ` embedded document with `*)` field gets created.

**Comment by ilijabojanovic** [comment]
Verified
