### ISSUE TITLE
tests failing (cannot connect to mongo db)

### ISSUE THREAD

**Issue by jensneuse** [TykTechnologies/tyk-pump#124]
If you follow the instructions from README.md it's not possible to make the tests running.
The tests expect a mongo db.
I'd like to add dockertest to spin up a mongo db for every test so that tests can run in any environment.
What kind of mongo does the test expect? Are there any requirements to be met, e.g. migrations, before running the tests?

**Comment by buger** [comment]
Note that it expects mongodb only if you are using mongodb pump (which is in default config). 

We do not have any specific new mongo features, so any 3.x+ version should work without issues (I think even 2.x+). 

No migrations needed.
