### ISSUE TITLE
Pump silent fails

### ISSUE THREAD

**Issue by mark-bradshaw** [TykTechnologies/tyk-pump#125]
We have pump 0.5.4 on ubuntu 18.  Periodically the pump stops working without the process failing.  There's no logging that indicates anything is amiss.  How can we diagnose the problem?

**Comment by asoorm** [comment]
How often is periodically?
Do you have any instrumentation in place?
Any server stats such as CPU / RAM at the point of failure? Anything else deployed on that host?

Please share your pump configs obfuscating any secrets / hostnames so that we can see how it's been setup.

**Comment by mark-bradshaw** [comment]
Periodically seems to be on the order of weeks.  We've enabled the built in instrumentation to statsd, and bumped the TYK_LOGLEVEL to debug.  There's no indications of CPU or RAM issues.  There's nothing else on the host other than basic ubuntu services.

**Comment by mark-bradshaw** [comment]
```{
  "analytics_storage_type": "redis",
  "analytics_storage_config": {
    "type": "redis",
    "enable_cluster": <%= @redis_enable_cluster %>,
    "host": "<%= @redis_host %>",
    "hosts": <%= @redis_hosts %>,
    "port": <%= @redis_port %>,
    "username": "",
    "password": "",
    "database": 0,
    "optimisation_max_idle": 400,
    "optimisation_max_active": 500
  },
  "purge_delay": 30,
  "pumps": {
    "csv": {
      "name": "csv",
      "meta": {
        "csv_dir": "/csvs/"
      }
    },
    "influx": {
      "name": "influx",
      "meta": {
        "database_name": "<%= @influx_db %>",
        "address": "<%= @influx_uri %>",
        "username": "",
        "password": "",
        "fields": [
          "request_time"
        ],
        "tags": [
          "method",
          "response_code",
          "api_name"
        ]
      }
    }
  },
  "dont_purge_uptime_data": true,
  "statsd_connection_string": "localhost:8125",
  "statsd_prefix": "apigatewaypump"
}
```
