### ISSUE TITLE
Add Elasticsearch 7 support

### ISSUE THREAD

**Issue by franfabrizio** [TykTechnologies/tyk-pump#139]
After upgrading our Elasticsearch cluster to 7, we found that we needed to update our pump.conf's Elasticsearch section to have  "document_type": "_doc" because Elasticsearch 7 removed document types (https://www.elastic.co/guide/en/elasticsearch/reference/master/removal-of-types.html) so you get an error if you try to assign a document type of "tyk_analytics". Unfortunately, simply removing the document_type field doesn't work because tyk_pump seems to default to "tyk_analytics" if a value is not provided. However, "_doc" works because this is compatible with ES 7 path names.

If you're getting an error each time tyk-pump tries to push a message to ES that says:

`elastic: Error 400 (Bad Request): Rejecting mapping update to [reindexed-v7-tyk_analytics_live] as the final mapping would have more than 1 type: [_doc, tyk_analytics] [type=illegal_argument_exception]"`

this is likely the issue.

**Comment by christtyk** [comment]
Would like to keep open, multiple requests for the same

**Comment by christtyk** [comment]
bump

**Comment by gregdelhon** [comment]
Done in Pump 1.5 https://github.com/TykTechnologies/tyk-pump/pull/385 
@franfabrizio

**Comment by tirelibirefe** [comment]
Am I doing something wrong?

```
        "elasticsearch": {
          "type": "elasticsearch",
          "meta": {
            "index_name": "tyk_analytics",
            "elasticsearch_url": "https://escluster-es-http.eck.svc.cluster.local:9200",
            "enable_sniffing": false,
            "document_type": "tyk_analytics",
            "rolling_index": true,
            "extended_stats": true,
            "version": "7",
            "user": "elastic",
            "passwd": "akdjoa7fq74tpq7",
            "tls": true,
            "tlsverify": false,
            "bulk_config":{
              "workers": 2,
              "flush_interval": 60
            }
          }
        }
      },
```

`level=fatal msg="Invalid version: Only 3, 5, 6 are valid values for this field"`

**Comment by tbuchaillot** [comment]
Hey @tirelibirefe! ES 7 support was introduced in [Tyk-pump 1.5](https://github.com/TykTechnologies/tyk-pump/releases/tag/v1.5.0)
Can you double-check what version are you using?
