### ISSUE TITLE
ability to shard & filter analytics to different data-sinks

### ISSUE THREAD

**Issue by asoorm** [TykTechnologies/tyk-pump#148]
It is possible to have multiple pumps of the same type. 

e.g. 3 CSV pumps (simplest, but non-sensical use-case).
Each sending analytics to different CSV files.

```
    "csv1": {
      "type": "csv",
      "meta": {
        "csv_dir": "./foo"
      }
    },
    "csv2": {
      "type": "csv",
      "meta": {
        "csv_dir": "./bar"
      }
    },
    "csv3": {
      "type": "csv",
      "meta": {
        "csv_dir": "./baz"
      }
    }
```

Proposal to allow sharding these analytics to send different data to different locations.

```
    "csv1": {
      "type": "csv",
      "filters": {
        "org_ids": ["org1"]
      },
      "meta": {
        "csv_dir": "./foo"
      }
    },
    "csv2": {
      "type": "csv",
      "filters": {
        "org_ids": ["org1","org2"]
      },
      "meta": {
        "csv_dir": "./bar"
      }
    },
    "csv3": {
      "type": "csv",
      "filters": {
        "org_ids": ["org3"]
      },
      "meta": {
        "csv_dir": "./baz"
      }
    }
```

As such, from the pump, we can separate out different organisations and send their analytics to different places.

> Using this API design, we can then incrementally add new filters as the need arises - e.g. based on API_ID. Meaning analytics for specific API can be sent to specific data-sinks.

It would be extremely powerful to be able to apply selectors - to whitelist fields from being able to be sent to those data-sinks.

```
    "csv3": {
      "type": "csv",
      "filters": {
        "org_ids": ["org3"]
      },
      "selectors": ["api_id", "latency", "code"]
      "meta": {
        "csv_dir": "./baz"
      }
```

In the above example, only org3's analytics would be sent to this pump, and only fields `api_id`, `latency`, `code`.

**Comment by tbuchaillot** [comment]
Related #212
