### ISSUE TITLE
Gracefully truncate or ignore data when size is bigger than 16MB

### ISSUE THREAD

**Issue by ConsM** [TykTechnologies/tyk-pump#154]
At the moment this will result in an error
 `Problem inserting to mongo collection: BSONObj size: X (0x28CB7F0) is invalid. Size must be between 0 and 16793600(16MB)`

**Comment by dencoded** [comment]
It seems like truncating data (as suggested in the title of this issue might be too agressive)

According to our implementation config param `max_insert_batch_size_bytes` should prevent sending data sets more than specified (default value `10MB`):
https://github.com/TykTechnologies/tyk-pump/blob/master/pumps/mongo.go#L344

Looks like it is not calculated correctly and tries to sends more which causes this issue.

I think we have a bug here: https://github.com/TykTechnologies/tyk-pump/blob/master/pumps/mongo.go#L330
we add size of raw request to itself, however response can be much bigger.

Looks like it was supposed to be size of raw request + size of raw response:
`len([]byte(thisItem.RawRequest)) + len([]byte(thisItem.RawResponse))`

**Comment by asoorm** [comment]
What @dencoded says makes sense. Also no need to do byte slice conversion, given that strings are immutable byte slices.

Separate issue - we should probably store `RawRequest` and `RawResponse` as byte slices to avoid copying & reduce memory allocations.

**Comment by letzya** [comment]
Btw, A client  got the same error in the aggregated pump as well.

**Comment by furkansenharputlu** [comment]
@asoorm @matiasinsaurralde Can you please see my solution?
