### ISSUE TITLE
No reconnecting to database.

### ISSUE THREAD

**Issue by eloyucu** [TykTechnologies/tyk-pump#16]
Hi everyone.

I was getting a error with the stats that pump must handle. The problem is that the stats wasn't being shown. The line that make reference in the syslog: 

> level=error msg="Problem inserting to mongo collection: EOF" 

It seems that tyk-pump cant reconnect to the mongo database. It seems that this [link](https://community.tyk.io/t/mongo-db-re-connection/158/3) is not totally correct (I mean, someone says that the problem is fixed... but no). 

I stop and restart mongo and I obtain this error, and then if I restart pump... it works again.

**Comment by lonelycode** [comment]
Which version are you running?

**Comment by eloyucu** [comment]
Ooopsss!! Sorry, I forgot put the versions...

tyk-dashboard -> 1.1.0.0
tyk-gateway     -> 2.1.0.2
tyk-pump         -> 0.2.0.0

Thanks.

**Comment by Preravana** [comment]
Hi, In documentation at pump.conf file it is provided host and hosts what does it mean actually. what should be the value of host and hosts? I am using Docker installation.

**Comment by eloyucu** [comment]
Hi @Preravana 

I think you can open a new issue for your question... because 1) it is a old issue 2) it is not related with yours.

Nice to meet you.
