### ISSUE TITLE
Provide an option to ignore specific tags from aggregated analytics

### ISSUE THREAD

**Issue by komalsukhani** [TykTechnologies/tyk-pump#162]
Mongo aggregate pump should provide a way to ignore specific tags from analytics. 
This is useful when `tag_headers` are used for most of APIs, which might result in exceed of mongo document size limit.

**Comment by maciejwojciechowski** [comment]
Can you please check, I still see tags on aggregated analytics.
In my pump.conf I have this
```
"mongo-pump-aggregate": {
            "name": "mongo-pump-aggregate",
            "meta": {
                "mongo_url": "mongodb://tyk-mongo:27017/tyk_analytics"
            },
            "ignore_tag_prefix_list": ["x-mw-"],
            "use_mixed_collection": true
        },
```
but in my aggregated analytics I see tags starting with `x-mw-` prefix
![image](https://user-images.githubusercontent.com/39672152/68673123-4d911680-0553-11ea-8239-4ee0812a3bea.png)

**Comment by maciejwojciechowski** [comment]
my config was bad, this option should go inside `meta`

**Comment by ilijabojanovic** [comment]
@marksou we need to document this

**Comment by maciejwojciechowski** [comment]
this setting on `"threshold_len_tag_list": 5` shows some rubbish in the log file:

```
[Nov 12 16:10:22]  WARN WARNING: Found more that 5 tag entries per document, which may cause performance issues with aggregate logs. List of most common tag-prefix: [api-4 ma]. You can ignore these tags using ignore_tag_prefix_list option
```

I would expect to see 5 mostly used tags in the list instead of 'api-4 ma'

**Comment by maciejwojciechowski** [comment]
I have also noticed that in case of MDCB and hybrid pump setup those new options somehow correlate with `aggregated` flag.
In my case when `aggregated: true` 
> ignore_tag_prefix_list works fine but
> threshold_len_tag_list warning is not shown on master pump

when `aggregated: false` 
> threshold_len_tag_list warning works fine on master pump but
> ignore_tag_prefix_list does not work (I see all tags again in mongo document)

**Comment by maciejwojciechowski** [comment]
After some discussion with @komalsukhani 
when `aggregated: false` the aggregated data is calculated on master pump. Thus, the `ignore_tag_prefix` must be also set on master pump. This is expected.

The only problem that needs fixing is the warning message not shown which needs MDCB changes.

**Comment by maciejwojciechowski** [comment]
One case is still failing. In MDCB scenario with hybrid pump (which has `aggregated=true`) the warning message is never shown on master pump (threshold_len_tag_list) and your traffic goes via hybrid gateway.

**Comment by maciejwojciechowski** [comment]
some update as configuring hybrid pump might not be straight forward.
When using MDCB setup with hybrid pump the option "threshold_len_tag_list" should go to different places depending on hybrid pump setup.
If hybrid's pump flag `"aggregated": false` we need to set `threshold_len_tag_list` in master pump.
If hybrid's pump flag `"aggregated": true` we need to set `threshold_len_tag_list` in sink (and warning message is logged here as well).
Just for everybody's FYI.

**Comment by maciejwojciechowski** [comment]
verified
