### ISSUE TITLE
Aggregate analytics document size grows more than 16MB

### ISSUE THREAD

**Issue by komalsukhani** [TykTechnologies/tyk-pump#164]
Currently, aggregate data is generated on hourly basis. That could be one the reason.
Aggregate pump should provide an option to record data per minute.

**Comment by ilijabojanovic** [comment]
@marksou we need to document this feature

**Comment by sedkis** [comment]
@buger @komalsukhani 
Can we please document this by adding mongo aggregate example to tyk pump readme?
