### ISSUE TITLE
Tyk pump not instrumenting Custom Analytics Tags in prometheus

### ISSUE THREAD

**Issue by anujmnit71** [TykTechnologies/tyk-pump#172]
Version
tyk-pump : 0.8.1

Referring this
https://tyk.io/docs/tyk-rest-api/api-definition-objects/custom-analytics/
I added "customtag1" as custom analytics tag 
In log browser , following tags are shown
Tags: 
customtag1-customtag1value
key-00000000 
org-5dae911e65fa6d0001c6a77d 
api-d3a9fe502a3845117b8c983f62be9784

whereas in Prometheus metrics only following is exported
{code="500",key="00000000"}

whereas my expected output
{code="500",key="00000000",customtag1="custom-tag1-value"}
so that I can perform analytics on custom tags using Prometheus as data source.

**Comment by sedkis** [comment]
not stale
