### ISSUE TITLE
Adding a Pump for Syslog

### ISSUE THREAD

**Issue by sedkis** [TykTechnologies/tyk-pump#189]
I want my pump to spit out my request and response logs to the standard output, or syslog.

I want a single entry for each request.   is this possible?  what would be the throughput capabilities?

**Comment by adelowo** [comment]
If a pump for standard output is going to be implemented, let's make it fluentd compatible.

**Comment by sedkis** [comment]
keep open!

**Comment by letzya** [comment]
@sedkis what's the benefit of it over csv? is it for dev env in which you want to quickly see the records or maybe something else? worse adding the use case and the necessity so it can be prioritise :)

**Comment by sedkis** [comment]
pr in progress
