### ISSUE TITLE
Support ElasticSearch batch operations

### ISSUE THREAD

**Issue by tbuchaillot** [TykTechnologies/tyk-pump#204]
Optimize the way we write in ES. 

The idea is changing the way we write now (for loop + sending one by one record) for the ES bulk API to send a batch of analytics records in one roundtrip.

**Comment by tbuchaillot** [comment]
Related #205

**Comment by maciejwojciechowski** [comment]
can we make pump logs more clear? currently I have ES `"bulk_actions":10` but with every request I send I see in logs
```
INFO elasticsearch-pump: Writing 1 records
```
I think with such settings it would make sense to log INFO every 10 records.
Is it easy to improve pump logging for this feature?

**Comment by maciejwojciechowski** [comment]
log problem will be handled separately

**Comment by maciejwojciechowski** [comment]
verified

**Comment by marksou** [comment]
When documenting the Batch features, I've spotted that we have miss-spelt `workers`. We have named it `wokers`.
