### ISSUE TITLE
TT-2925 Improve elasticsearch log 

### ISSUE THREAD

**Issue by maciejwojciechowski** [TykTechnologies/tyk-pump#229]
Related to https://github.com/TykTechnologies/tyk-pump/issues/204

ES pump is now sending data in batch, e.g. every 1000 records. However, the way we log messages remained the 'old' way, so every x seconds (defined in `purge_delay`) we log info message
```
[1430]  INFO elasticsearch-pump: Writing 1 records
```
I think it would be better if we log that message when the batch is truly sent, so in our example above - every 1000 records. 
This of course should be based on ES `bulk_config` options, depending when the batch is really sent.

**Comment by joshblakeley** [comment]
not stale

**Comment by Bouwdie** [comment]
For this we can use the Before and/or After functions of the bulk processor :+1:

**Comment by gregdelhon** [comment]
Covered in pump 1.5 🎉
