### ISSUE TITLE
Build not working locally due to failing dependency: github.com/influxdata/influxdb/client/v2 

### ISSUE THREAD

**Issue by nezhar** [TykTechnologies/tyk-pump#236]
This happens when installing the dependencies: `go get -t -d -v ./...`

```
package github.com/influxdata/influxdb/client/v2: cannot find package "github.com/influxdata/influxdb/client/v2" in any of:
        /usr/lib/golang/src/github.com/influxdata/influxdb/client/v2 (from $GOROOT)
        /home/nezhar/go/src/github.com/influxdata/influxdb/client/v2 (from $GOPATH)
```

I have a fresh installed go on fedora:
`go version go1.13.6 linux/amd64`

Due to this failure the build and the tests are also not working:
```
11:21 $ go build -v ./...
pumps/influx.go:9:2: cannot find package "github.com/influxdata/influxdb/client/v2" in any of:
        /usr/lib/golang/src/github.com/influxdata/influxdb/client/v2 (from $GOROOT)
        /home/nezhar/go/src/github.com/influxdata/influxdb/client/v2 (from $GOPATH)
```

I also tried the the setup as described in the `.travis.yml` with the same issue.

Is there something that I'm missing?

**Comment by anx-hnezbeda** [comment]
I needed to do this in a difernet way because of how the dependencies are resolved in go: https://github.com/anx-hnezbeda/tyk-pump/blob/anexia/.github/workflows/build.yml.

Since https://github.com/TykTechnologies/tyk-pump/pull/251 was merged this this is not relevant anymore.
