### ISSUE TITLE
Tyk Pump Memory Leak - Splunk

### ISSUE THREAD

**Issue by TheRealDwright** [TykTechnologies/tyk-pump#238]
We have observed a memory leak with Tyk when using the pump with Splunk Cloud. We have tested this on multiple versions including:

- v0.7.2
- v0.8.4

We run the pump in a Docker container on Kubernetes however the leak can be observed regardless of what OS you run on. We are using the official docker images at tykio/tyk-pump-docker-pub.

The rate at which memory is consumed for our production environment is approximately 500mb every 25 minutes.

Particulars for us is:

- Splunk Cloud
- Redis Data Store

**Comment by TheRealDwright** [comment]
Hi @buger,

Just wondering if you've had a chance to look at this please?

**Comment by TheRealDwright** [comment]
Just commenting that this is still a problem for us, we're going to have our engineering team take a look at possible cause.

**Comment by christtyk** [comment]
Hey @TheRealDwright sorry for the delay here

Is it still an issue for you/have you found out anything further? We're reviewing internally now

**Comment by tbuchaillot** [comment]
@TheRealDwright hey! Could you give us more details on this?

**Comment by christtyk** [comment]
If we could get the API definition, GW/Pump/Splunk configs that will help us to reproduce

**Comment by gregdelhon** [comment]
@TheRealDwright closing the issue, if it's still a problem, let us know.
