### ISSUE TITLE
ElasticSearch missing properties for HTTP Authorization Header & Kafka missing properties for SASL JAAS (username + password) and others

### ISSUE THREAD

**Issue by bmonteiro** [TykTechnologies/tyk-pump#246]
Hey guys, 

Usually tools like ES require authentication specially when using SaaS it is possible to pass those Auth Tokens (-H "Authorization: ApiKey $ECE_API_KEY") in the configuration? 
With this option it is not possible to pass the info like: http://user:pass@host... because it needs to be an HTTP header.

DOCS: https://www.elastic.co/guide/en/cloud-enterprise/current/Authentication.html#login

The same for Kafka some SaaS Kafka give you this data:

bootstrap.servers=hostname:9093

sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="token" password="api-key-secret"

sasl.mechanism=PLAIN

security.protocol=SASL_SSL

ssl.protocol=TLSv1.2

Can those be configured somehow via pump.conf ?

FYI @letzya @buger @asoorm

**Comment by bmonteiro** [comment]
This is a good source for Kafka https://docs.confluent.io/current/kafka/authentication_sasl/index.html

**Comment by letzya** [comment]
@tbuchaillot - for ES can we also add option for API key not just basic auth?

**Comment by buger** [comment]
Library we use for Kafka should support SASL https://github.com/segmentio/kafka-go/pull/223

**Comment by matiasinsaurralde** [comment]
Cherry-picked and merged to the release branch: https://github.com/TykTechnologies/tyk-pump/commit/8268812a1009f76afdf663950a9e60c704a38fad
