### ISSUE TITLE
tt-356 StatsD pump: Move method to the separate tag instead of embedding to the path

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk-pump#250]
Embedding it to the path makes it hard to aggregate the data. 
https://github.com/TykTechnologies/tyk-pump/blob/master/pumps/statsd.go#L99

Behavior should be optional and be turned on by some flag, for backward compatibility reasons.

**Comment by gregdelhon** [comment]
@buger do you recall who was the client?

**Comment by andyo-tyk** [comment]
This was fixed in Pump 1.6.
