### ISSUE TITLE
T-2923 Better API for initializing clients

### ISSUE THREAD

**Issue by mcandre** [TykTechnologies/tyk-pump#253]
Please drop the `Start` method, which users can easily forget to execute.

Instead, make the struct private and use a constructor to generate a fully valid client with event queue ready to use.

**Comment by gregdelhon** [comment]
Thanks for the suggestion @mcandre - looks like a nice and simple improvement. We will look into this for the next pump release.

**Comment by tbuchaillot** [comment]
@mcandre  do you have more details about this request?

**Comment by andyo-tyk** [comment]
We're at a loss with this one, so closing due to lack of detail.
