### ISSUE TITLE
TT-2924 Deprecate PostEvent

### ISSUE THREAD

**Issue by mcandre** [TykTechnologies/tyk-pump#254]
More network overhead than the available EnqueueEvent method.

**Comment by gregdelhon** [comment]
thanks for the suggestion @mcandre , will review with the engineering team!

**Comment by tbuchaillot** [comment]
@mcandre do you have more details about this request?

**Comment by andyo-tyk** [comment]
We don't understand this request, so without further explanation will have to close it.
