### ISSUE TITLE
bug: healthcheck endpoint issues

### ISSUE THREAD

**Issue by asoorm** [TykTechnologies/tyk-pump#256]
https://tyk.io/docs/tyk-configuration-reference/tyk-pump-configuration/#health-check

1. Default port is same port as the gateway - that makes no sense - as this means the pump will not be able to bind to 8080 if the gateway is running, or the gateway won't start if the pump is running (and both are on same machine).

2. Listens on Localhost - meaning that K8s or in docker - you can't call the health endpoint.

3. We spin up a go routine - and can't cancel / stop it.

```
go server.ServeHealthCheck(SystemConfig.HealthCheckEndpointName, 
SystemConfig.HealthCheckEndpointPort)
```

4. We don't catch the error from http handler or do anything with it - so if the pump healthcheck tries to start on port 8080, cannot bind because that port is owned by gateway, then we don't know about it. We think the pump is down. 

https://github.com/TykTechnologies/tyk-pump/blob/53720da433bc22d881292d4eb6b778bd698ef736/server/server.go#L35

**Comment by tbuchaillot** [comment]
Hey, @asoorm about point 3. Why would you want to cancel/stop the goroutine with the health check?
