### ISSUE TITLE
Missing v1.0.0 docker image

### ISSUE THREAD

**Issue by NgariNdungu** [TykTechnologies/tyk-pump#275]
The image for the latest release doesn't seem to be available from [dockerhub](https://hub.docker.com/r/tykio/tyk-pump-docker-pub/tags). The github image is also behind

**Comment by anx-hnezbeda** [comment]
Looks like it is available now: https://hub.docker.com/layers/tykio/tyk-pump-docker-pub/v1.0.0/images/sha256-a944ddd360f6d10804f47cc5c5ee24b48c3cf6a372035c803041516bd899ff34?context=explore

**Comment by NgariNdungu** [comment]
Awesome, thanks for the heads-up
