### ISSUE TITLE
TT-556 Pump logs should not show username and password of the MongoDB URL

### ISSUE THREAD

**Issue by n2linux** [TykTechnologies/tyk-pump#282]
**Branch/Environment**
- Branch: Master
- Environment: All

**Describe the bug**
Pump logs should not show username and password of MongoDB URL.

**Reproduction steps**
1.  Have mongo pump enabled 
2. Look at the logs to see the full mongo URL w/username and pass

**Actual behavior**
Currently in the pump logs, the entire mongo url is shown, e.g.:
`mongodb://username:password@my-mongo-instance:27017/tyk_analytics`

**Expected behavior**
The username and password should not be included, similar to how we did for Elasticsearch in: https://github.com/TykTechnologies/tyk-pump/pull/258

**Additional context**
Reported by SLA customer in ZD #11176

**Comment by letzya** [comment]
We should check other pumps as well while we fix this one
