### ISSUE TITLE
tt-2926 Elasticsearch pump does not shutdown gracefully - potential data loss

### ISSUE THREAD

**Issue by Bouwdie** [TykTechnologies/tyk-pump#297]
With the introduction of the bulk worker in the Elasticsearch pump we have introduced a default in-memory queue of 1000 or 5mb worth of analytics messages going to Elasticsearch. With its introduction it has become the default behavior. There is no mechanism in place to gracefully shutdown the pump and it subsidiary worker pumps. When the pump application would get terminated any number between 0 and 999 messages could get lost. Running in a Kubernetes environment containers should be able to get stopped and restarted (on another node) without the loss of data. Especially for something as important as analytical data we should provide users with mechanism that is safe without potential data loss.

**Comment by gregdelhon** [comment]
Thanks @Bouwdie adding it to our backlog for future releases.

**Comment by letzya** [comment]
@buger can you have a look, this is quite important, especially with ephemeral containers. We could do gracefull shutdown or at least allow users to choose not use bulk writing?

**Comment by Bouwdie** [comment]
@gregdelhon any idea when this improvement will land?

**Comment by letzya** [comment]
@Bouwdie - a [PR](https://github.com/TykTechnologies/tyk-pump/pull/388) by @tbuchaillot if you want to try it.

**Comment by gregdelhon** [comment]
@Bouwdie - it's now tried and test and GA in Pump 1.5 🎉  Let us know when you got your hands if you have any feedback. 
Also, this suggestion was really good, if you have any more don't hesitate to share!
