### ISSUE TITLE
Prometheus pump superflouous error

### ISSUE THREAD

**Issue by Zavierazo** [TykTechnologies/tyk-pump#370]
Hi, we have a problem with prometheus pump. When we start applications everything works fine but after couple of days(sometimes take weeks to happen) we see this error on log:

`2021/07/13 07:51:22 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)`

When it starts to happen, it only happens once an hour or more, but little by little it happens more and more until there comes a time that happens in each pump cycle.

When this happens we stop receiving metrics from prometheus until we restart the pump. Doing some research it seems that it may be related to the prometheus client.  Maybe the library should be updated because currently we are using a very old version (v1.0.0)

https://github.com/prometheus/client_golang/issues/672

Regards

**Comment by gregdelhon** [comment]
@Zavierazo - thanks for this. Looks like it is related to Prometheus indeed but we should double check. 
@tbuchaillot what do you think? Anything we can do on our side?

**Comment by tbuchaillot** [comment]
@gregdelhon it seems this was fixed in https://github.com/prometheus/client_golang/pull/724 (prometheus-client v1.5.1). We need to update our client version in pump :)

**Comment by Zavierazo** [comment]
Hi, I think that the timeout for this pump should also be reviewed since it seems that the one passed by configuration is not being respected.

Config Example:
`{
    "analytics_storage_type": "redis",
    "analytics_storage_config": {
        "type": "redis",
        "enable_cluster": true,
        "hosts": {
          "xxxxxxx":"6379"
        },
        "username": "",
        "password": "xxxxxx",
        "database": 0,
        "optimisation_max_idle": 100,
        "optimisation_max_active": 0
    },
    "purge_delay": 6,
    "health_check_endpoint_name": "health",
    "health_check_endpoint_port": 8080,
    "pumps": {
        "kafka": {
            "name": "kafka",
            "timeout": 5,
            "filters": {
                "skip_response_codes": [ 200 ]
            },
            "meta": {
                "broker": [
                    "essc-kafka-lmp.sharedaws.service:9092"
                ],
                "client_id": "tyk-pump",
                "topic": "tyk-pump",
                "timeout": 5,
                "compressed": true
            }
        },
        "prometheus": {
          "timeout": 5,
          "type": "prometheus",
          "meta": {
              "listen_address": ":8182",
              "path": "/metrics"
          }
        }
    },
    "dont_purge_uptime_data": true
}`

In theory every 6 seconds in a purge cycle and the pumps have a 5-second timeout indicated but if we look at logs we see that the timeout is not being respected

`Aug 17 08:50:31 tyk-pump-03n8 tyk-pump: time="Aug 17 08:50:31" level=info msg="Writing 6489 records..."
Aug 17 08:50:33 tyk-pump-03n8 tyk-pump: 2021/08/17 08:50:33 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:50:33 tyk-pump-03n8 tyk-pump: 2021/08/17 08:50:33 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:50:36 tyk-pump-03n8 tyk-pump: time="Aug 17 08:50:36" level=warning msg="Timeout Writing to: Prometheus Pump"
Aug 17 08:50:38 tyk-pump-03n8 tyk-pump: 2021/08/17 08:50:38 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:50:39 tyk-pump-03n8 tyk-pump: 2021/08/17 08:50:39 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:50:41 tyk-pump-03n8 tyk-pump: time="Aug 17 08:50:41" level=error msg="Multi command failed: read tcp 10.197.1.223:37674->10.197.6.75:6379: i/o timeout"
Aug 17 08:50:42 tyk-pump-03n8 tyk-pump: 2021/08/17 08:50:42 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:50:42 tyk-pump-03n8 tyk-pump: 2021/08/17 08:50:42 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:50:49 tyk-pump-03n8 tyk-pump: 2021/08/17 08:50:49 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:50:50 tyk-pump-03n8 tyk-pump: 2021/08/17 08:50:50 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:50:53 tyk-pump-03n8 tyk-pump: 2021/08/17 08:50:53 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:50:53 tyk-pump-03n8 tyk-pump: 2021/08/17 08:50:53 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:50:55 tyk-pump-03n8 tyk-pump: time="Aug 17 08:50:55" level=info msg="Writing 2087 records..."
Aug 17 08:50:58 tyk-pump-03n8 tyk-pump: 2021/08/17 08:50:58 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:51:03 tyk-pump-03n8 tyk-pump: time="Aug 17 08:51:03" level=error msg="Multi command failed: read tcp 10.197.1.223:37904->10.197.6.75:6379: i/o timeout"
Aug 17 08:51:03 tyk-pump-03n8 tyk-pump: 2021/08/17 08:51:03 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:51:03 tyk-pump-03n8 tyk-pump: 2021/08/17 08:51:03 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:51:03 tyk-pump-03n8 tyk-pump: 2021/08/17 08:51:03 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:51:08 tyk-pump-03n8 tyk-pump: 2021/08/17 08:51:08 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:51:09 tyk-pump-03n8 tyk-pump: 2021/08/17 08:51:09 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:51:12 tyk-pump-03n8 tyk-pump: 2021/08/17 08:51:12 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:51:13 tyk-pump-03n8 tyk-pump: 2021/08/17 08:51:13 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:51:19 tyk-pump-03n8 tyk-pump: time="Aug 17 08:51:19" level=info msg="Writing 2633 records..."
Aug 17 08:51:20 tyk-pump-03n8 tyk-pump: 2021/08/17 08:51:20 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:51:20 tyk-pump-03n8 tyk-pump: 2021/08/17 08:51:20 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:51:22 tyk-pump-03n8 tyk-pump: 2021/08/17 08:51:22 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:51:22 tyk-pump-03n8 tyk-pump: 2021/08/17 08:51:22 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:51:27 tyk-pump-03n8 tyk-pump: time="Aug 17 08:51:27" level=error msg="Multi command failed: read tcp 10.197.1.223:38014->10.197.6.75:6379: i/o timeout"
Aug 17 08:51:31 tyk-pump-03n8 tyk-pump: 2021/08/17 08:51:31 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:51:31 tyk-pump-03n8 tyk-pump: 2021/08/17 08:51:31 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:51:33 tyk-pump-03n8 tyk-pump: 2021/08/17 08:51:33 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:51:33 tyk-pump-03n8 tyk-pump: 2021/08/17 08:51:33 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:51:41 tyk-pump-03n8 tyk-pump: 2021/08/17 08:51:41 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:51:41 tyk-pump-03n8 tyk-pump: 2021/08/17 08:51:41 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:51:42 tyk-pump-03n8 tyk-pump: time="Aug 17 08:51:42" level=info msg="Writing 2600 records..."
Aug 17 08:51:44 tyk-pump-03n8 tyk-pump: 2021/08/17 08:51:44 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:51:46 tyk-pump-03n8 tyk-pump: 2021/08/17 08:51:46 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:51:47 tyk-pump-03n8 tyk-pump: time="Aug 17 08:51:47" level=warning msg="Timeout Writing to: Prometheus Pump"
Aug 17 08:51:52 tyk-pump-03n8 tyk-pump: 2021/08/17 08:51:52 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:51:52 tyk-pump-03n8 tyk-pump: 2021/08/17 08:51:52 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:51:55 tyk-pump-03n8 tyk-pump: 2021/08/17 08:51:55 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:51:56 tyk-pump-03n8 tyk-pump: 2021/08/17 08:51:56 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:52:02 tyk-pump-03n8 tyk-pump: 2021/08/17 08:52:02 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:52:03 tyk-pump-03n8 tyk-pump: 2021/08/17 08:52:03 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:52:05 tyk-pump-03n8 tyk-pump: 2021/08/17 08:52:05 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:52:07 tyk-pump-03n8 tyk-pump: 2021/08/17 08:52:07 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:52:12 tyk-pump-03n8 tyk-pump: 2021/08/17 08:52:12 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:52:14 tyk-pump-03n8 tyk-pump: 2021/08/17 08:52:14 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:52:17 tyk-pump-03n8 tyk-pump: 2021/08/17 08:52:17 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:52:17 tyk-pump-03n8 tyk-pump: 2021/08/17 08:52:17 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:52:21 tyk-pump-03n8 tyk-pump: 2021/08/17 08:52:21 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:52:22 tyk-pump-03n8 tyk-pump: 2021/08/17 08:52:22 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:52:23 tyk-pump-03n8 tyk-pump: 2021/08/17 08:52:23 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:52:24 tyk-pump-03n8 tyk-pump: 2021/08/17 08:52:24 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:52:31 tyk-pump-03n8 tyk-pump: 2021/08/17 08:52:31 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:52:32 tyk-pump-03n8 tyk-pump: 2021/08/17 08:52:32 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:52:33 tyk-pump-03n8 tyk-pump: 2021/08/17 08:52:33 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:52:34 tyk-pump-03n8 tyk-pump: 2021/08/17 08:52:34 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:52:40 tyk-pump-03n8 tyk-pump: time="Aug 17 08:52:40" level=info msg="Writing 8000 records..."
Aug 17 08:52:40 tyk-pump-03n8 tyk-pump: 2021/08/17 08:52:40 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:52:41 tyk-pump-03n8 tyk-pump: 2021/08/17 08:52:41 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:52:42 tyk-pump-03n8 tyk-pump: 2021/08/17 08:52:42 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:52:42 tyk-pump-03n8 tyk-pump: 2021/08/17 08:52:42 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:52:45 tyk-pump-03n8 tyk-pump: time="Aug 17 08:52:45" level=warning msg="Timeout Writing to: Prometheus Pump"
Aug 17 08:52:50 tyk-pump-03n8 tyk-pump: 2021/08/17 08:52:50 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:52:50 tyk-pump-03n8 tyk-pump: time="Aug 17 08:52:50" level=error msg="Multi command failed: read tcp 10.197.1.223:38114->10.197.6.75:6379: i/o timeout"
Aug 17 08:52:52 tyk-pump-03n8 tyk-pump: 2021/08/17 08:52:52 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:52:52 tyk-pump-03n8 tyk-pump: 2021/08/17 08:52:52 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:52:53 tyk-pump-03n8 tyk-pump: 2021/08/17 08:52:53 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:52:59 tyk-pump-03n8 tyk-pump: 2021/08/17 08:52:59 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:52:59 tyk-pump-03n8 tyk-pump: 2021/08/17 08:52:59 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:53:03 tyk-pump-03n8 tyk-pump: 2021/08/17 08:53:03 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:53:03 tyk-pump-03n8 tyk-pump: 2021/08/17 08:53:03 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:53:04 tyk-pump-03n8 tyk-pump: time="Aug 17 08:53:04" level=info msg="Writing 1991 records..."
Aug 17 08:53:11 tyk-pump-03n8 tyk-pump: 2021/08/17 08:53:11 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:53:11 tyk-pump-03n8 tyk-pump: 2021/08/17 08:53:11 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:53:12 tyk-pump-03n8 tyk-pump: 2021/08/17 08:53:12 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
Aug 17 08:53:12 tyk-pump-03n8 tyk-pump: 2021/08/17 08:53:12 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)`

**Comment by gregdelhon** [comment]
@Zavierazo closing this as pump 1.5 should solve it :) let us know if you have any questions/remarks.
