### ISSUE TITLE
Health Check

### ISSUE THREAD

**Issue by ConsM** [TykTechnologies/tyk-pump#39]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
N/A

**What is the expected behavior?**
Tyk Pump should have a health check functionality

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All

**Comment by theholy7** [comment]
+1 for this.

**Comment by lilithyang2018** [comment]
+1
