### ISSUE TITLE
mongo pump doesn't work with mongo 5

### ISSUE THREAD

**Issue by aaimsh** [TykTechnologies/tyk-pump#398]
I configured pump.conf to connect to a mongo 5.0.4 container, then the pump stuck on a loop with the following output:
`
Search...
time="Oct 24 12:21:06" level=info msg="## Tyk Analytics Pump, 1.5.0 ##" 
time="Oct 24 12:21:06" level=info msg="--> [REDIS] Creating single-node client" 
time="Oct 24 12:21:06" level=info msg="Serving health check endpoint at http://localhost:8083/health ..." 
time="Oct 24 12:21:06" level=info msg=Init collection_name=user url="***:***@database:27017/admin?authSource=admin" 
time="Oct 24 12:21:06" level=info msg="-- No max batch size set, defaulting to 10MB" 
time="Oct 24 12:21:06" level=info msg="-- No max document size set, defaulting to 10MB" 
time="Oct 24 12:21:06" level=error msg="Mongo connection failed. Retrying." dialinfo="***:***@database:27017/admin?authSource=admin" error="server returned error on SASL authentication step: BSON field 'saslContinue.mechanism' is an unknown field." 
time="Oct 24 12:21:11" level=error msg="Mongo connection failed. Retrying." dialinfo="***:***@database:27017/admin?authSource=admin" error="server returned error on SASL authentication step: BSON field 'saslContinue.mechanism' is an unknown field."
time="Oct 24 12:21:16" level=error msg="Mongo connection failed. Retrying." dialinfo="***:***@database:27017/admin?authSource=admin" error="server returned error on SASL authentication step: BSON field 'saslContinue.mechanism' is an unknown field."` 

When I downgraded mongo container to 4.0.0 image, it worked as expected.

**Comment by caroltyk** [comment]
Hi @aaimsh , we have added support for MongoDB 5.0 recently in Pump v1.8.0

Please check out the release notes: https://github.com/TykTechnologies/tyk-pump/releases/tag/v1.8.0
