### ISSUE TITLE
Error using Elastisearch 5+

### ISSUE THREAD

**Issue by raphaeltricae** [TykTechnologies/tyk-pump#41]
I have this error message using ES 5+ with tyk pump, 

> Elasticsearch connection failed: no Elasticsearch node available

it works fine when I use ES 2+, this is my pump.conf 

`{
    "analytics_storage_type": "redis",
    "analytics_storage_config": {
        "type": "redis",
        "host": "localhost",
        "port": 6379,
        "hosts": null,
        "username": "",
        "password": "",
        "database": 0,
        "optimisation_max_idle": 100,
        "optimisation_max_active": 0,
        "enable_cluster": false
    },
    "purge_delay": 10,
    "pumps": {
        "elasticsearch": {
            "name": "elasticsearch",
            "meta": {
                "index_name": "tyk_analytics",
                "elasticsearch_url": "127.0.0.1:9200",
                "enable_sniffing": false,
                "document_type": "tyk_analytics",
                "rolling_index": false,
                "extended_stats": false,
                "version": "5"
            }
        }
    },
    "dont_purge_uptime_data": true
}`

I'm using tyk pump 0.4.2

**Comment by danilobreda** [comment]
Same here, with 6+. @buger can you help us with this?
