### ISSUE TITLE
[TT-3067] Use self signed certificate for elasticsearch

### ISSUE THREAD

**Issue by dar9468** [TykTechnologies/tyk-pump#411]
I would like to be able to disable the verification of self-signed certificates for elasticsearch. 
![image](https://user-images.githubusercontent.com/17763421/147919922-83b180ba-3a51-43a4-94bb-b8ee83a98d83.png)

**Comment by gregdelhon** [comment]
Thanks @dar9468 we will discuss internally and get back to you

**Comment by andyo-tyk** [comment]
Hi @dar9468,
We've scheduled a fix for this in our next Pump release - v1.7 - planned for early December.

**Comment by caroltyk** [comment]
This has been fixed in Pump v1.7.0. Please check out the release notes here! https://github.com/TykTechnologies/tyk-pump/releases/tag/v1.7.0
