### ISSUE TITLE
Query parameters in "request_uri_full" field

### ISSUE THREAD

**Issue by bkomac** [TykTechnologies/tyk-pump#420]
How to include original request query params in "request_uri_full" analytics?

**Comment by oluwaseyeayinla** [comment]
Hi @bkomac, not sure if you have found a resolution but I think we have something similar in our [elasticsearch.go pump](https://github.com/TykTechnologies/tyk-pump/blob/2d7830be9caef1a4067e5b1a3db029b2c5745723/pumps/elasticsearch.go#L408)

 `"request_uri_full": record.RawPath,`

We would be happy to assist you on our [community forums](https://community.tyk.io/), if you have any further questions.
