### ISSUE TITLE
Pump tries to init MongoDB, even if not configured - then hangs forever

### ISSUE THREAD

**Issue by ChristianCiach** [TykTechnologies/tyk-pump#44]
My tyk-pump 0.4.2 hangs on startup:

> tyk-pump[24603]: time="Sep  4 14:54:55" level=info msg="## Tyk Analytics Pump, v0.4.2 ##"
> tyk-pump[24603]: time="Sep  4 14:54:55" level=debug msg="CSV Initialized"
> tyk-pump[24603]: time="Sep  4 14:54:55" level=info msg="Init Pump: CSV Pump"
> tyk-pump[24603]: time="Sep  4 14:54:55" level=info msg="-- No max batch size set, defaulting to 10MB"
> tyk-pump[24603]: time="Sep  4 14:54:55" level=info msg="-- No max document size set, defaulting to 10MB"

That is the complete log of tyk-pump. 

Looking at the code, the string "No max document size set" is only logged by the MongoDB-pumps. I think it hangs forever at "m.connect()".

But I don't want to use MongoDB and I haven't configured it. This is my pump.conf:

```
{
    "analytics_storage_type": "redis",
    "analytics_storage_config": {
        "type": "redis",
        "host": "localhost",
        "port": 6379,
        "hosts": null,
        "username": "",
        "password": "",
        "database": 0,
        "optimisation_max_idle": 100,
        "optimisation_max_active": 0,
        "enable_cluster": false
    },
    "purge_delay": 10,
    "pumps": {
	"csv": {
            "name": "csv",
            "meta": {
                "csv_dir": "./"
            }
	}
    }
}
```

**Comment by buger** [comment]
Try setting `dont_purge_uptime_data` to `true`

**Comment by ChristianCiach** [comment]
Thanks, I just found this out by looking at the code :) I also found this:
