### ISSUE TITLE
Statsd pump: Allow escaping/replacing of dots in tag values

### ISSUE THREAD

**Issue by ChristianCiach** [TykTechnologies/tyk-pump#45]
The Statsd pump concatenates the values of the configured tags using a dot as the separator, see `statsd.go` at line 119. This itself is fine, as statsd metrics are usually separated by dots. In fact, the [prometheus statsd-exporter](https://github.com/prometheus/statsd_exporter) expects this to be the case.

Unfortunately, some tag values (like `ip_address` or sometimes even `path`) contain dots themselves, thus breaking (or at least ruining) the generated metric name. Because of this, I would like to have the option to replace the dots inside the tag values with another character, like the underscore for example.

**Comment by exustash** [comment]
bump!
