### ISSUE TITLE
[TT-6341]Bug: pumps/prometheus.go Init method

### ISSUE THREAD

**Issue by MagicalBomb** [TykTechnologies/tyk-pump#473]
commit f2396ed, tag  1.6.0
pumps/prometheus.go line:145

&metrics point to the same memory address, so elements in p.customMetrics will always keep the same

**Comment by pagemag** [comment]
@MagicalBomb Thank you for posting here. We will discuss this internally and we'll get back to you.

**Comment by andyo-tyk** [comment]
Hi @MagicalBomb,
We've scheduled a fix for this in our next Pump release - v1.7 - planned for early December.

**Comment by caroltyk** [comment]
This has been released in Pump v1.7.0

https://github.com/TykTechnologies/tyk-pump/releases?q=1.7
