### ISSUE TITLE
RFC: Prometheus: `tyk_http_status_per_path` cardinality issues leading to scrape timeouts.

### ISSUE THREAD

**Issue by hsyed-dojo** [TykTechnologies/tyk-pump#491]
Hello Folks,

I'm looking at contributing a tactical fix for our API gateway team. Completely new to Tyk so apologies if am overlooking existing workarounds.

The `path` field in `tyk_http_status_per_path` is generating too much cardinality which in turn is timing out our scrape jobs. We'd like to exclude this particular metric family from exposition entirely.

I propose adding a `DisabledMetrics []string` (name?) to `PrometheusConf` and any such metrics families get their `PrometheusMetric.enabled` flipped to false. 

If this sounds good I'm happy to submit a PR.

**Comment by tbuchaillot** [comment]
Hey @hsyed-dojo! 

It sounds good indeed! Please rise a PR and add me as reviewer 👍
