### ISSUE TITLE
Raw data is sent in base64 to Elasticsearch

### ISSUE THREAD

**Issue by jmleoni** [TykTechnologies/tyk-pump#52]
When you use Which is pretty useless for use with kibana if you want to search in the body of the requests or the answers.
There should be some automated based64decode before raw_data is sent to elasticsearch

**Comment by christtyk** [comment]
@komalsukhani @joshblakeley do you know if this was done? I have a customer asking about this issue.

**Comment by christtyk** [comment]
I need this to stay open as a client has requested it, though I thought it was already done. @komalsukhani do you know if we've already implemented it?

**Comment by letzya** [comment]
Marked as bug since this feature doesn't work
