### ISSUE TITLE
[TT-8761] Bug: Tyk prometheus inconsistent label cardinality error due to separator

### ISSUE THREAD

**Issue by kaushal-move** [TykTechnologies/tyk-pump#600]
**Description**:

When processing an analytics record with an API name or path containing the `--` separator used to join label values (e.g., web--test-beta), an "inconsistent label cardinality" error occurs and causes tyk pump to crash. This is because the API name/path is split incorrectly when using the same separator, resulting in an unexpected number of label values.

**Steps to reproduce:**

1. Create API with API name containing `--` (e.g., web--test-beta).
2. Configure Tyk prometheus pump with custom metric and add the label `api_name`
3. Once the API is called and the prometheus pump process the analytics record, observe the panic: inconsistent label cardinality: expected * label values but got *

**Possible solution:**

To resolve the issue, use a different separator for joining and splitting the label values that does not appear in any of the actual values.

**Additional context:**

See the provided code and analytics record for more information on how the issue occurs. The issue seems to stem from the Inc, Observe, and Expose functions in the code, where the keys for the counterMap and histogramMap are generated by joining the label values with a double hyphen (--).

**Comment by caroltyk** [comment]
Thanks again for the contribution @kaushal-move we are going to include this in Pump 1.8.1 - Planned for the end of May 2023.
