### ISSUE TITLE
tyk-pump: error: unknown long flag '--c', try --help

### ISSUE THREAD

**Issue by ayyappaappana** [TykTechnologies/tyk-pump#64]
Hi All,

Please help me with this, i am running TYK_quickstart in my local virtual machine. It worked fine for me last week. but, i jst removed docker images and reload using docker-compose fortunately without any change in the files.

is throwing this error.

**Docker Version:**
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64
 Experimental: false

pump.conf
--------------
{
	"analytics_storage_type": "redis",
    "analytics_storage_config": {
        "type": "redis",
        "host": "redis",
        "port": 6379,
        "hosts": null,
        "username": "",
        "password": "",
        "database": 0,
        "optimisation_max_idle": 100,
        "optimisation_max_active": 0,
        "enable_cluster": false
    },
    "purge_delay": 2,
    "pumps": {
        "mongo": {
            "name": "mongo",
            "meta": {
                "collection_name": "tyk_analytics",
                "mongo_url": "mongodb://mongo:27017/tyk_analytics"
            }
        }
    },
    "uptime_pump_config": {
        "collection_name": "tyk_uptime_analytics",
        "mongo_url": "mongodb://mongo:27017/tyk_analytics"
    },
    "dont_purge_uptime_data": false
}

**Looking for help on this.**

**docker-compose file:**

version: '2'
services:
    tyk_redis:
        image: redis:3.2
        hostname: redis
        ports:
            - "6379:6379"
        networks:
            gateway:
                aliases:
                    - redis
    tyk_mongo:
        image: mongo:3.0
        command: ["mongod", "--smallfiles"]
        hostname: mongo
        ports:
            - "27017:27017"
        networks:
            gateway:
                aliases:
                    - mongo
    tyk_dashboard:
        image: tykio/tyk-dashboard:latest
        ports:
            - "3000:3000"
            - "5000:5000"
        volumes:
            - ./tyk_analytics.conf:/opt/tyk-dashboard/tyk_analytics.conf
        networks:
            - gateway
    tyk_pump:
        image: tykio/tyk-pump-docker-pub:latest
        networks:
            - gateway
        volumes:
            - ./pump.conf:/opt/tyk-pump/pump.conf
    tyk_gateway:
        image: tykio/tyk-gateway:latest
        ports:
            - "80:8080"
            - "8080:8080"
        volumes:
            - ./tyk.conf:/opt/tyk-gateway/tyk.conf
        networks:
            - gateway

networks:
    gateway:

**Comment by excieve** [comment]
Hi @ayyappaappana! Thanks for your report, this should be fixed in the latest `tykio/tyk-pump-docker-pub` image.
