### ISSUE TITLE
Add ElasticSearch 6 support

### ISSUE THREAD

**Issue by carlosjgp** [TykTechnologies/tyk-pump#68]
The V6 client is already there!
https://gopkg.in/olivere/elastic.v6

**Comment by matiasinsaurralde** [comment]
@carlosjgp Hi, did you use `go get github.com/TykTechnologies/tyk-pump` to fetch the  package?

**Comment by carlosjgp** [comment]
No, I didn't. This is the first time I'm coding in GoLang sorry if I'm asking a silly question... @matiasinsaurralde But should I get the package I'm compiling?

I run `go get github.com/TykTechnologies/tyk-pump` and `go build -v ./...` but I'm still having the same error

**Comment by matiasinsaurralde** [comment]
@carlosjgp Try using:
```
go get -u github.com/TykTechnologies/tyk-pump
cd $GOPATH/src/github.com/TykTechnologies/tyk-pump
go build
```

**Comment by carlosjgp** [comment]
By the way... I did install the latest GoLang version following this instructions
https://golang.org/doc/install

**Comment by carlosjgp** [comment]
By running this commands
```
go get -u github.com/TykTechnologies/tyk-pump
cd $GOPATH/src/github.com/TykTechnologies/tyk-pump
go build
```
I get this output
```
_/github/tyk-pump
# _/github/tyk-pump
./main.go:188:56: cannot use writeToPumps (type func([]interface {}, *"github.com/gocraft/health".Job, time.Time)) as type func([]interface {}, *"github.com/TykTechnologies/tyk-pump/vendor/github.com/gocraft/health".Job, time.Time) in argument to demo.GenerateDemoData
```

**Comment by danilobreda** [comment]
@carlosjgp did you resolved this problem? im trying to use the 5+ but only errors on the pump :/
@lonelycode  do you have some informations about this error to try help us? whats the recommendations. Thanks

**Comment by carlosjgp** [comment]
Sorry @danilobreda, my team decided that we have never used those metrics so the effort to add ES6 to TykPump is not worthy.

I'm still quite keen on trying to do it on my free time as first GoLang coding experience. But I need to read a little bit more about the language and set up my environment properly

**Comment by lonelycode** [comment]
Re-opening this issue because there seems to be a second version check that means the ES6 driver can never be used here: 

https://github.com/TykTechnologies/tyk-pump/blob/master/pumps/elasticsearch.go#L113

**Comment by buger** [comment]
Good spot, fixed now
