### ISSUE TITLE
Sweep: Add track_all_path support for the prometheus pump

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk-pump#712]
So we have this cardinality issue in [Prometheus pump](https://github.com/TykTechnologies/tyk-pump/blob/master/pumps/prometheus.go). And we decided that it should be fixed the same way as it done in [mongo aggregate pump](https://github.com/TykTechnologies/tyk-pump/blob/master/pumps/mongo_aggregate.go) , by introducing `track_all_path` boolean variable, and it should check if analytics record trackable or not. 

Here are the detailed steps with file names for addressing the Prometheus pump cardinality issue:
1. In `pumps/prometheus.go`, add a new TrackAllPaths bool field to the PrometheusConf struct.
2. In WriteData, add a check for TrackAllPaths before processing each record:

```
for _, v := range data {

  // Check if we should process this record
  if p.conf.TrackAllPaths || v.TrackPath {

    // Normal record processing

  }

}
```

3. Add tests in something like pumps/prometheus_test.go to validate the behavior.

**Comment by buger** [comment]
sweep:

**Comment by buger** [comment]
sweep:

**Comment by buger** [comment]
sweep:

**Comment by buger** [comment]
sweep:

**Comment by kevinlu1248** [comment]
sweep:

**Comment by wwzeng1** [comment]
Hey @buger, the message is too long. We're looking into this now. This may be due to using GPT 3.5

**Comment by buger** [comment]
@wwzeng1 you mean message in the Issue description? Also PR which it generated contained quite obvious mistake, weird. But yes, maybe its 3.5

**Comment by caroltyk** [comment]
Fixed by https://github.com/TykTechnologies/tyk-pump/pull/716
