### ISSUE TITLE
Add log browser index to analytics collections

### ISSUE THREAD

**Issue by excieve** [TykTechnologies/tyk-pump#74]
Currently there's no efficient index created for analytics collections in MongoDB. This results in the dashboard log browser failing to display anything due to mongo timeouts on large enough collections. This also causes excessive load on the MongoDB itself.

So far the following composite index is proved to work pretty well:
```.js
db.tyk_analytics.createIndex({"timestamp" : -1, "orgid" : 1, "apiid" : 1, "apikey" : 1, "responsecode" : 1}, {background: true})
```

This index starts with the descending `timestamp`, which is always present in the log browser requests and includes all the optional parameters that it can use. Note that `orgid` should not be required for on-prem installations with a single org.

The index above can grow quite large too though so possibly just limiting it to `timestamp` + `orgid` (when needed) can be enough. Especially for the log browser case, which shows only a limited number of results per page.

In addition to this, pump currently creates a number of composite indices that are never utilised due to starting with an `_id` field. Those should be removed.

**Comment by ilijabojanovic** [comment]
Verified
