### ISSUE TITLE
TT-12057 Splunk pump ignores HTTP proxy environment variables

### ISSUE THREAD

**Issue by jonathanfoster** [TykTechnologies/tyk-pump#816]
It appears the Splunk pump client isn't using HTTP proxy environment variables. I'm running Tyk Pump in a restricted environment that requires all outbound connections use the an HTTP proxy. Requests to the Splunk collector URL are timing out because they're attempting to connect directly instead of using the proxy. I confirmed HTTP_PROXY, HTTPS_PROXY, and NO_PROXY environment variables are all set.

I believe this could be caused by [setting the HTTP default client transport here](https://github.com/TykTechnologies/tyk-pump/blob/aa0961a3e2c40a5aa763a15a641b1651b72c770c/pumps/splunk.go#L305) and not setting proxy to `http.ProxyFromEnvironment`.

**Comment by caroltyk** [comment]
@jonathanfoster Just an update we're working on it and will fix this in our next release.

**Comment by vverbani** [comment]
@jonathanfoster came across this comment from the issue #4102... checked the internal ticket associated with this and it appears this was pushed to pump v1.10.0
