### ISSUE TITLE
High cardinality active series with prometheus

### ISSUE THREAD

**Issue by geNAZt** [TykTechnologies/tyk-pump#817]
When having path enabled it will generate a active series for every path seen on access log. This generates multiple million active series which is a problem. For istio we use https://istio.io/latest/docs/tasks/observability/metrics/classify-metrics/ for this reason. 

Since we have a migration to tyk and need a path based metric for our user journey logging. It would be nice if tyk either detects routes from OAS and publishes that as path/route. If thats currently not possible it would be nice if we can have post processors or plugins which can manipulate metrics before they are published.

**Comment by caroltyk** [comment]
Hi @geNAZt ! Would you mind to share with us pattern of the paths and how you would like to group them?

**Comment by geNAZt** [comment]
Sure, the APIs we have use IDs (UUID) as part of the URL Path:

For example:

GET /cards/v1/card/{cardId} which results in multiple thousand urls containing UUID in their path. I would like to only see a `/cards/v1/card/{cardId}` label inside the metric so that i can monitor the operation "Getting a card from API". Currently the only way is to have 

`sum (rate(tyk_http_status_per_path_total{env="{{.env}}", api_name="{{.api}}", method=~"{{.method}}", path=~"{{.path}}", code=~"{{.code}}"}[{{.window}}]))`

With path set to `/cards/v1/card/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$`. 

As you can see with that example we have a uncapped grow rate of active metrics. I attached a export of active series amount and their increments before we cut the metric exporting for now

<img width="572" alt="Screenshot 2024-05-04 at 11 01 26" src="https://github.com/TykTechnologies/tyk-pump/assets/3252854/1a462c98-ad68-425b-8718-45d7a592941e">

**Comment by oluwaseyeayinla** [comment]
@geNAZt I think this https://community.tyk.io/t/reducing-cardinality-of-tyk-pump-analytics/7070 may be what you are looking for 

Let us know if it helps

**Comment by geNAZt** [comment]
Yes that would help, is it planned that OAS support can generate those from the parameters given in URLs?

For example: 

https://swagger.io/docs/specification/describing-parameters/

Could for `/users/{userId}` generate `/api_prefix/users/\d+` 

I guess we can generate all our path normalisations with custom patterns for now and generate them from our OAS files.

Thanks
