### ISSUE TITLE
No release or update to changelog for 1.9.0

### ISSUE THREAD

**Issue by l3ender** [TykTechnologies/tyk-pump#821]
We see tyk-pump version 1.9.0 has been released in package cloud, but we don't see the associated release on the github repo or the repo's changelog.

https://packagecloud.io/tyk/tyk-pump/

Can same please be added to this repo? Thanks!

**Comment by caroltyk** [comment]
Thank you, @l3ender. We will reinstate it promptly.

Meanwhile, kindly refer to the release notes on Tyk's official website at: https://tyk.io/docs/product-stack/tyk-pump/release-notes/pump-1.9/

**Comment by caroltyk** [comment]
Release doc updated: https://github.com/TykTechnologies/tyk-pump/releases/tag/v1.9.0 🎉
