### ISSUE TITLE
Metric prefix for statsd pump

### ISSUE THREAD

**Issue by talentrydev** [TykTechnologies/tyk-pump#86]
It seems like currently it's not possible to specify a prefix to apply to all metrics pushed by the statsd pump (or am I wrong?). It would really be useful to be able to create a namespace for tyk metrics (even hardcoding it to `tyk` would be an improvement.

**Comment by talentrydev** [comment]
Created a feature request on tyk forum and linked this issue there: 
https://community.tyk.io/t/pump-statsd-prefix/3032

**Comment by buger** [comment]
Looking at code, static prefix is there, but it not getting used when initializing statsd driver https://github.com/TykTechnologies/tyk-pump/blob/master/pumps/statsd.go
