### ISSUE TITLE
Pump do not create init files on Amazon Linux

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk-pump#87]
AMI image: 
amzn-ami-hvm-2018.03.0.20181129-x86_64-gp2 (ami-08935252a36e25f85)

If you install Pump, it does not create anything in /etc/init.d

**Comment by excieve** [comment]
Amazon Linux is based on CentOS 6, which uses Upstart 0.6.x init system as described in [our docs](https://tyk.io/docs/get-started/with-tyk-on-premise/#a-name-init-systems-a-init-systems). Init system configs are available in `/etc/init/` and usable through a set of `start`, `stop`, `status`, etc. commands or through `initctl` as [documented by Upstart](http://upstart.ubuntu.com/cookbook/#utilities).
