### ISSUE TITLE
Add Docker Image for Tyk Pump

### ISSUE THREAD

**Issue by JosephEarl** [TykTechnologies/tyk-pump#9]
To allow it to easily be used with Docker quick start and Docker based setups.

* Dockerfile for releases (currently 0.2.0.0): https://github.com/JosephEarl/tyk-pump-docker/blob/master/Dockerfile
* Dockerfile for nightly: https://github.com/JosephEarl/tyk-pump-docker/blob/nightly/Dockerfile

The pump should be configured with the default redis/mongo host names in the Docker quick start.

**Comment by lonelycode** [comment]
There is already a docker image for tyk pump:

https://github.com/lonelycode/tyk-pump-docker-pub

It is used in the quickstart?

**Comment by JosephEarl** [comment]
Missed that.
