### ISSUE TITLE
All pumps should be configurable with env vars

### ISSUE THREAD

**Issue by excieve** [TykTechnologies/tyk-pump#92]
In some setups (e.g. running containers) it might be easier to do configuration through environment variables. We already support that for MongoDB pumps using `PMP_MONGO`, `PMP_MONGOAGG`, etc. env prefixes but that's missing from the ElasticSearch pump and possibly some others. This needs to be reviewed and implemented for all the pumps.

**Comment by buger** [comment]
I guess it needs to be not only configurable, but also enabled by env vars as well. So if default config does not include ES, we set env vars for ES and it gets turned on.

I believe we can do it automatically for all pumps at once. We know the pre-defined name of each pump, so prefix will be always: `PMP_{upper(name)}`, so we need to check if env variables with such prefix exist, based on that "enable"/"auto-create" related pumps, and call envconfig before initializing each pump.

**Comment by eloo** [comment]
Hello, 
is the usage of PMP_MONGO and others somewhere documented? Because i've not seen this in the documentation already.
thx

**Comment by theholy7** [comment]
@excieve , what is the status of this issue? How do you recommend configuring an elastic search pump if it has basic auth, and you don't want to commit it to a repo?

**Comment by asoorm** [comment]
It is currently possible to have multiple pumps of the same type. How could we support environment variables, whilst still allowing configuration of multiple pumps of same type?

e.g. `PMP_CSV_1_CSVDIR`, `PMP_CSV_2_CSVDIR`, `PMP_CSV_3_CSVDIR`? or would we simply only allow single pump type if Env vars are used?

Related: https://github.com/TykTechnologies/tyk-pump/issues/148

**Comment by jlucktay** [comment]
From the [`envconfig` README](https://github.com/kelseyhightower/envconfig#supported-struct-field-types), it seems to me that since the pump configs are stored in a map like `map[string]PumpConfig` if the `PumpConfig` struct were to implement the `encoding.TextUnmarshaler` interface (which is also on `envconfig`s supported types list) then that would cover some of this issue off.

**Comment by eloo** [comment]
i guess this is still open

**Comment by jlucktay** [comment]
The [custom decoders](https://github.com/kelseyhightower/envconfig#custom-decoders) in `envconfig` would be another option to implement these with.

**Comment by drpebcak** [comment]
Would love to see this supported because without it, tyk-pump is hard/impossible to configure properly when using the helm chart.

**Comment by asoorm** [comment]
To give a concrete use-case for this in a k8s setup:

Let's take the datadog pump. DataDog runs as a daemonset - one agent per node inside K8s cluster.
It would be desirable to inject the host IP in the datadog Agent's address.

```
    "dogstatsd": {
      "type": "dogstatsd",
      "meta": {
        "address": "localhost:8125", <---------------THIS?
        "namespace": "pump",
        "async_uds": true,
        "async_uds_write_timeout_seconds": 2,
        "buffered": true,
        "buffered_max_messages": 32,
        "tags": [
          "method",
          "response_code",
          "api_version",
          "api_name",
          "api_id",
          "org_id",
          "tracked",
          "path",
          "oauth_id"
        ]
      }
    },
```

**Comment by sedkis** [comment]
now released!
