### ISSUE TITLE
ability to blacklist/whitelist fields for each pump

### ISSUE THREAD

**Issue by asoorm** [TykTechnologies/tyk-pump#98]
For example, ability to explicitly exclude request/response data from CSV pump - because that might be used to ship to a SaaS service, but include in the mongo pump for internal inspection.

**Comment by letzya** [comment]
Could it be confusing if the config file has both whitelist and blacklist fields?
Since now it's all the fields and we add functionality, maybe have an override list? or just blacklist since you can see which fields you don't want and you cannot forget fields that you want or was not aware of ?

**Comment by asoorm** [comment]
Well i was thinking that a whitelist was more appropriate. If new columns are added into the request analytics - the output should not change - especially with CSV.

**Comment by cajund** [comment]
+1 on this one. In my case, I need to block the `RewRequest` and `RawResponse` fields as my app is HIPAA sensitive and these elements will have the PII that needs to remain protected.
